export const SET_USER = 'SET_USER';
export const SET_RESERVATION_DATA = 'SET_RESERVATION_DATA';
export const SET_COUPON = 'SET_COUPON';
export const SET_WAITNUM = 'SET_WAITNUM';
export const BEGIN_DATA_REQUEST = 'BEGIN_DATA_REQUEST';
export const SUCCESS_DATA_REQUEST = 'SUCCESS_DATA_REQUEST';
export const FAIL_DATA_REQUEST = ' FAIL_DATA_REQUEST';
export const CANT_FIND_DATA = 'CANT_FIND_DATA';
