export default {
  // home: '/',
  bookingConfirm: '/',
  reservationInfo: '/reservationInfo',
  tableNumInfo: '/tableNumInfo',
  noReserved: '/noReserved',
  waiting: '/waiting',
  menu: '/menu',
  pricePlan: '/pricePlan',
  mealHabits: '/mealHabits',
  order: '/order',
  orderRecord: '/orderRecord',
  checkout: '/checkout',
  feedback: '/feedback',
  checkoutOptions: '/checkoutOptions',
  couponChoose: '/couponChoose',
  mealFinish: '/mealFinish',
  member: '/member',
  consumerRecord: '/consumerRecord',
  coupon: '/coupon',
  habitSetting: '/habitSetting',
};
